# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            EmmanuelSW
tagline:          'Blog'
description:      'My personal blog.'
url:              http://emmanuelsw.me
baseurl:          
commentsystem:    example
disqus:           example

author:
  name:           Emmanuel Deossa
  url:            https://github.com/emmanuelsw

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/emmanuel_sw
    desc:         Twitter

  - icon:         github
    url:          https://github.com/emmanuelsw
    desc:         Github

  - icon:         facebook-alt
    url:          https://www.facebook.com/
    desc:         Facebook

  - icon:         linkedin-alt
    url:          https://www.linkedin.com/in/emmanuel-deossa-b51031127
    desc:         Linkedin

menu:
  - title:        Inicio
    url:          /

  - title:        Acerca de
    url:          /about

copyright:
  author:         Emmanuel Deossa
  url:            emmanuelsw.me 
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
