markdown: kramdown
permalink: /blog/:title

plugins:
  - jekyll-paginate

# Setup
title:            EmmanuelSW
tagline:          'Blog'
description:      'My personal blog.'
url:              http://emmanuelsw.me
theme_color:      7E9576  
paginate:         5
baseurl:          

icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

author:
  name:           Emmanuel Deossa
  url:            https://github.com/emmanuelsw

social:
  - icon:         twitter
    url:          https://twitter.com/emmanuel_sw
    desc:         Twitter

  - icon:         github
    url:          https://github.com/emmanuelsw
    desc:         Github

  - icon:         facebook
    url:          https://www.facebook.com/EmmanuelSW
    desc:         Facebook

  - icon:         linkedin-alt
    url:          https://www.linkedin.com/in/emmanuel-deossa-b51031127
    desc:         Linkedin

menu:
  - title:        Inicio
    url:          /

  - title:        Acerca de
    url:          /about

copyright:
  author:         Emmanuel Deossa
  url:            emmanuelsw.me 
  type_url:       http://creativecommons.org/licenses/by-nc/2.5
